export const products = [
 {id:"PR-NUT-001",name:"Almonds",slug:"almonds",category:"nuts",price:780,oldPrice:900,packages:[{size:"100g",price:260},{size:"250g",price:520},{size:"500g",price:780},{size:"1kg",price:1480}],rating:4.8,reviews:128,short:"Premium whole almonds, carefully selected and freshly packed.",description:"Crunchy, naturally rich almonds selected for everyday snacking and nutrition-focused meals.",ingredients:"100% almonds",nutrition:"Per 100g: Protein 21g • Fat 49g • Carbohydrate 22g",benefits:"A nutrient-dense source of protein, healthy fats and fibre.",use:"Enjoy as a snack, add to oats, salads or smoothies.",storage:"Store airtight in a cool, dry place.",related:["cashew-nuts","walnuts","premium-nut-mix"]},
 {id:"PR-NUT-002",name:"Cashew Nuts",slug:"cashew-nuts",category:"nuts",price:820,oldPrice:950,packages:[{size:"100g",price:280},{size:"250g",price:550},{size:"500g",price:820},{size:"1kg",price:1550}],rating:4.9,reviews:94,short:"Creamy, premium cashews with a clean natural crunch.",description:"Selected whole cashews with a rich texture, packed for freshness.",ingredients:"100% cashew nuts",nutrition:"Per 100g: Protein 18g • Fat 44g • Carbohydrate 30g",benefits:"Provides protein, minerals and unsaturated fats.",use:"Snack on their own or use in desserts and savoury recipes.",storage:"Keep sealed away from heat and moisture.",related:["almonds","pistachios","premium-nut-mix"]},
 {id:"PR-NUT-003",name:"Walnuts",slug:"walnuts",category:"nuts",price:920,oldPrice:1050,packages:[{size:"100g",price:320},{size:"250g",price:620},{size:"500g",price:920},{size:"1kg",price:1750}],rating:4.8,reviews:73,short:"Premium walnut halves with a naturally earthy flavour.",description:"Freshly packed walnut halves for wholesome snacking and recipes.",ingredients:"100% walnuts",nutrition:"Per 100g: Protein 15g • Fat 65g • Carbohydrate 14g",benefits:"A source of healthy fats and plant protein.",use:"Add to breakfast bowls, baked goods or salads.",storage:"Refrigerate after opening for longer freshness.",related:["almonds","pistachios","premium-nut-mix"]},
 {id:"PR-NUT-004",name:"Pistachios",slug:"pistachios",category:"nuts",price:980,oldPrice:1100,packages:[{size:"100g",price:340},{size:"250g",price:650},{size:"500g",price:980},{size:"1kg",price:1880}],rating:4.7,reviews:61,short:"Premium pistachios selected for flavour and freshness.",description:"Naturally delicious pistachios, packed in a clean, convenient format.",ingredients:"100% pistachios",nutrition:"Per 100g: Protein 20g • Fat 45g • Carbohydrate 28g",benefits:"A convenient source of plant protein and fibre.",use:"Perfect for snacking, desserts and festive dishes.",storage:"Store sealed in a cool, dry place.",related:["cashew-nuts","almonds","premium-nut-mix"]},
 {id:"PR-SEE-001",name:"Pumpkin Seeds",slug:"pumpkin-seeds",category:"seeds",price:520,oldPrice:590,packages:[{size:"100g",price:190},{size:"250g",price:350},{size:"500g",price:520},{size:"1kg",price:990}],rating:4.7,reviews:46,short:"Clean, crunchy pumpkin seeds for daily nutrition.",description:"Carefully selected pumpkin seeds with a satisfying crunch.",ingredients:"100% pumpkin seeds",nutrition:"Per 100g: Protein 30g • Fat 49g • Carbohydrate 11g",benefits:"A source of plant protein, fibre and minerals.",use:"Sprinkle over salads, oats or yoghurt.",storage:"Seal tightly and keep dry.",related:["chia-seeds","sunflower-seeds","premium-seed-mix"]},
 {id:"PR-SEE-002",name:"Chia Seeds",slug:"chia-seeds",category:"seeds",price:460,oldPrice:520,packages:[{size:"100g",price:170},{size:"250g",price:320},{size:"500g",price:460},{size:"1kg",price:860}],rating:4.9,reviews:112,short:"Tiny nutrient-rich chia seeds for smoothies and breakfast bowls.",description:"Premium chia seeds selected for clean texture and everyday use.",ingredients:"100% chia seeds",nutrition:"Per 100g: Protein 17g • Fat 31g • Carbohydrate 42g",benefits:"A plant-based source of fibre and healthy fats.",use:"Soak in water or milk, or add to smoothies and oats.",storage:"Store sealed in a cool, dry place.",related:["pumpkin-seeds","flax-seeds","premium-seed-mix"]},
 {id:"PR-SEE-003",name:"Sunflower Seeds",slug:"sunflower-seeds",category:"seeds",price:390,oldPrice:450,packages:[{size:"100g",price:150},{size:"250g",price:270},{size:"500g",price:390},{size:"1kg",price:740}],rating:4.6,reviews:38,short:"Fresh sunflower kernels with a gentle nutty flavour.",description:"Clean, crunchy sunflower seeds for snacks and recipes.",ingredients:"100% sunflower seeds",nutrition:"Per 100g: Protein 21g • Fat 51g • Carbohydrate 20g",benefits:"Contains protein, fibre and vitamin-rich nutrients.",use:"Enjoy as a snack or sprinkle over salads and cereal.",storage:"Keep airtight and dry.",related:["pumpkin-seeds","flax-seeds","premium-seed-mix"]},
 {id:"PR-SEE-004",name:"Flax Seeds",slug:"flax-seeds",category:"seeds",price:360,oldPrice:420,packages:[{size:"100g",price:140},{size:"250g",price:250},{size:"500g",price:360},{size:"1kg",price:680}],rating:4.6,reviews:29,short:"Whole flax seeds for wholesome everyday meals.",description:"Freshly packed flax seeds with a subtle nutty flavour.",ingredients:"100% flax seeds",nutrition:"Per 100g: Protein 18g • Fat 42g • Carbohydrate 29g",benefits:"A plant-based source of fibre and healthy fats.",use:"Grind before adding to smoothies, porridge or baking.",storage:"Refrigerate after opening for best quality.",related:["chia-seeds","pumpkin-seeds","premium-seed-mix"]},
 {id:"PR-SPC-001",name:"Organic Turmeric",slug:"organic-turmeric",category:"spices",price:280,oldPrice:320,packages:[{size:"100g",price:140},{size:"250g",price:250},{size:"500g",price:280},{size:"1kg",price:520}],rating:4.8,reviews:52,short:"Aromatic turmeric powder for everyday cooking.",description:"Fine turmeric powder selected for colour, aroma and freshness.",ingredients:"100% turmeric",nutrition:"Naturally occurring spice nutrients.",benefits:"Adds vibrant colour and warm flavour to meals.",use:"Use in curries, rice, marinades and warm drinks.",storage:"Keep sealed away from light and moisture.",related:["organic-cinnamon","organic-black-pepper","organic-spice-blends"]},
 {id:"PR-SPC-002",name:"Organic Cinnamon",slug:"organic-cinnamon",category:"spices",price:340,oldPrice:390,packages:[{size:"100g",price:160},{size:"250g",price:280},{size:"500g",price:340},{size:"1kg",price:640}],rating:4.8,reviews:41,short:"Warm, fragrant cinnamon for sweet and savoury recipes.",description:"Aromatic cinnamon prepared for daily culinary use.",ingredients:"100% cinnamon",nutrition:"Naturally occurring spice nutrients.",benefits:"Adds a warm, naturally sweet aroma to recipes.",use:"Add to tea, coffee, oats, baking and curries.",storage:"Keep dry and tightly sealed.",related:["organic-turmeric","organic-cardamom","organic-spice-blends"]},
 {id:"PR-SPC-003",name:"Organic Black Pepper",slug:"organic-black-pepper",category:"spices",price:320,oldPrice:360,packages:[{size:"100g",price:150},{size:"250g",price:270},{size:"500g",price:320},{size:"1kg",price:600}],rating:4.7,reviews:35,short:"Bold black pepper for everyday seasoning.",description:"Fragrant black pepper selected for a balanced bite and aroma.",ingredients:"100% black pepper",nutrition:"Naturally occurring spice nutrients.",benefits:"Adds depth and warmth to savoury meals.",use:"Grind over soups, salads, eggs and curries.",storage:"Keep airtight in a dry place.",related:["organic-turmeric","organic-cardamom","organic-spice-blends"]},
 {id:"PR-SPC-004",name:"Organic Cardamom",slug:"organic-cardamom",category:"spices",price:650,oldPrice:720,packages:[{size:"50g",price:300},{size:"100g",price:520},{size:"250g",price:650},{size:"500g",price:1200}],rating:4.8,reviews:24,short:"Fragrant green cardamom for tea and desserts.",description:"Premium cardamom pods selected for a fresh aromatic profile.",ingredients:"100% cardamom",nutrition:"Naturally occurring spice nutrients.",benefits:"Adds a distinctive floral aroma to food and drinks.",use:"Crush lightly for tea, rice dishes and desserts.",storage:"Store airtight away from heat.",related:["organic-cinnamon","organic-black-pepper","organic-spice-blends"]},
 {id:"PR-MIX-001",name:"Premium Nut Mix",slug:"premium-nut-mix",category:"nut-mixes",price:890,oldPrice:990,packages:[{size:"250g",price:520},{size:"500g",price:890},{size:"1kg",price:1680}],rating:4.9,reviews:88,short:"A premium blend of selected nuts for convenient snacking.",description:"A balanced mix of premium nuts prepared for busy days and wholesome snacking.",ingredients:"Almonds, cashews, walnuts, pistachios",nutrition:"Varies by blend; see pack label.",benefits:"Convenient variety of plant-based nutrients.",use:"Enjoy by the handful or add to breakfast bowls.",storage:"Keep sealed in a cool, dry place.",related:["almonds","cashew-nuts","pistachios"]},
 {id:"PR-MIX-002",name:"Premium Seed Mix",slug:"premium-seed-mix",category:"seed-mixes",price:590,oldPrice:680,packages:[{size:"250g",price:360},{size:"500g",price:590},{size:"1kg",price:1120}],rating:4.8,reviews:57,short:"A versatile blend of nutritious seeds.",description:"A convenient combination of selected seeds for daily meals.",ingredients:"Pumpkin, chia, sunflower and flax seeds",nutrition:"Varies by blend; see pack label.",benefits:"Adds plant-based variety, fibre and healthy fats to meals.",use:"Sprinkle over yoghurt, salads, oats and smoothies.",storage:"Seal after each use.",related:["chia-seeds","pumpkin-seeds","flax-seeds"]},
 {id:"PR-MIX-003",name:"Healthy Superfood Mix",slug:"healthy-superfood-mix",category:"superfoods",price:720,oldPrice:820,packages:[{size:"250g",price:420},{size:"500g",price:720},{size:"1kg",price:1380}],rating:4.8,reviews:49,short:"A convenient mix designed for nutritious everyday meals.",description:"A thoughtfully assembled mix for breakfast bowls, smoothies and snacks.",ingredients:"Selected nuts, seeds and natural ingredients; see pack label.",nutrition:"Varies by blend; see pack label.",benefits:"Convenient way to add variety to meals.",use:"Add to smoothies, oats or yoghurt.",storage:"Keep sealed and dry.",related:["premium-seed-mix","premium-nut-mix","chia-seeds"]},
 {id:"PR-HON-001",name:"Natural Honey",slug:"natural-honey",category:"honey",price:520,oldPrice:590,packages:[{size:"250g",price:320},{size:"500g",price:520},{size:"1kg",price:980}],rating:4.8,reviews:101,short:"Pure, naturally sweet honey for everyday use.",description:"Natural honey packed for convenient use in drinks, breakfast and recipes.",ingredients:"100% honey",nutrition:"Naturally occurring sugars; see pack label.",benefits:"A naturally sweet alternative for many everyday uses.",use:"Drizzle over toast, oats or mix into warm beverages.",storage:"Store at room temperature; crystallisation may occur naturally.",related:["premium-honey","healthy-superfood-mix","organic-cinnamon"]},
 {id:"PR-HON-002",name:"Premium Honey",slug:"premium-honey",category:"honey",price:720,oldPrice:820,packages:[{size:"250g",price:420},{size:"500g",price:720},{size:"1kg",price:1350}],rating:4.9,reviews:67,short:"A premium honey selection with a rich natural taste.",description:"Carefully selected honey presented as a premium pantry staple.",ingredients:"100% honey",nutrition:"Naturally occurring sugars; see pack label.",benefits:"A naturally sweet pantry ingredient.",use:"Use in breakfast, beverages, marinades and desserts.",storage:"Store tightly closed at room temperature.",related:["natural-honey","organic-cinnamon","healthy-superfood-mix"]}
];
export const categories = [
 {slug:"nuts",name:"Nuts",icon:"🥜",description:"Premium almonds, cashews, walnuts and pistachios."},
 {slug:"seeds",name:"Seeds",icon:"🌱",description:"Wholesome seeds for breakfast, snacks and recipes."},
 {slug:"spices",name:"Spices",icon:"🌿",description:"Aromatic natural spices for everyday cooking."},
 {slug:"nut-mixes",name:"Premium Nut Mixes",icon:"✨",description:"Convenient blends of selected premium nuts."},
 {slug:"seed-mixes",name:"Premium Seed Mixes",icon:"🌾",description:"Balanced seed blends for nutritious meals."},
 {slug:"honey",name:"Honey",icon:"🍯",description:"Natural sweetness for everyday wellness."},
 {slug:"superfoods",name:"Healthy Superfoods",icon:"🍃",description:"Convenient mixes for nutrition-focused routines."}
];
export function getProduct(slug){return products.find(p=>p.slug===slug)}
export function categoryProducts(slug){return products.filter(p=>p.category===slug)}
